### ISSUE TITLE
IntegerField instead of CharField

### ISSUE THREAD

**Issue by intellisense** [dracos/django-date-extensions#10]
I understand the choice of `CharField` for `ApproximateDateField` but a `PositiveIntegerField` would be a better choice as that will allow sorting as well. E.g. can be used in `order_by`. What are your thoughts on this? (If you are agree I can create a pull request)

**Comment by intellisense** [comment]
Yes you are right. Thanks!

**Comment by int-ua** [comment]
But Positive**Small**IntegerField would take less space AFAIU. What are the benefits of using `CharField`?

**Comment by dracos** [comment]
How would a `PositiveSmallIntegerField` hold enough values for the possible entries of the field? I doubt the difference makes any perceivable difference within the context of an entire Django project.

The benefits of using CharField include having a database representation that matches how e.g. MySQL stores approximate dates, for ease of inspection.

**Comment by int-ua** [comment]
Maybe I understood it wrong, I didn't check how approximate dates are stored, I thought that it was number or NULL only.
