### ISSUE TITLE
__unicode__ method for ApproximateDate class

### ISSUE THREAD

**Issue by hfx** [dracos/django-date-extensions#15]
Hi guys,

I ran into a UnicodeEncodeError ('ascii' codec can't encode characters in position 0-5: ordinal not in range(128), The string that could not be encoded/decoded was: Январь 1996) when rendering a template using django-date-extensions ApproximateDateField together with djangos built-in i18n translation framework (languages English and Russian).

Turns out that a missing __unicode__ method for the ApproximateDate class seems to be responsible as renaming the __str__ method (line 47 in fields.py) to __unicode__ fixed the problem.

Maybe you could consider adding it upstream. 

Great thanks for the very useful extension package, you saved me a lot of time and trouble!

Cheers,
Felix

**Comment by dracos** [comment]
Sorry for the huge delay in replying to you here. You're quite correct, this was badly written. I have hopefully fixed it in #21 (in a python2/3 compatible way), along with a test! Thanks for letting me know.
