### ISSUE TITLE
url patterns have changed since django 1.7

### ISSUE THREAD

**Issue by pmi123** [dracos/django-date-extensions#18]
Trying to run on django 2.0 I got this error:
  File "/home/mark/python-projects/django_date_extensions/example/urls.py", line 1, in <module>
    from django.conf.urls import patterns
ImportError: cannot import name 'patterns'

In urls.py, you have:
```
from django.conf.urls import patterns
from .views import view

urlpatterns = patterns(
    '',
    (r'^$', view),
)
```
In django 2.0 forward, I believe it should be 
```
from django.urls import path
from .views import view

urlpatterns =[
    path('', view),
]
```

**Comment by dracos** [comment]
Thanks! I've fixed this for Django 2, won't switch to `path` until dropping 1.11 support.
