### ISSUE TITLE
ImportError: cannot import name 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by kavonjon** [dracos/django-date-extensions#22]
Seems this might have to do with version support for django, and the use of the six package. For example: https://github.com/jjkester/django-auditlog/issues/231

In my case:
python 3.6.9
django: 3.0.5

models.py:
from django_date_extensions.fields import ApproximateDateField

settings.py:
INSTALLED_APPS = [
    ...
    'django_date_extensions'
    ....]

on makemigrations:
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

**Comment by dracos** [comment]
Yes, I'm afraid this does not support Django 3 at the moment (looks like that shouldn't be hard to fix, though, but I'd like to keep old compatibility if at all possible...).

**Comment by cizario** [comment]
i encountered the same error with `django 3.1`
as quick fix (hack) till an official update i commented in `venv/Lib/site-packages/django_date_extensions/field.py` those tow lines
```
..

# from django.utils.encoding import python_2_unicode_compatible  # HERE since the function is no more available
..

@total_ordering
# @python_2_unicode_compatible  # HERE
class ApproximateDate(object):
    """A date object that accepts 0 for month or day to mean we don't
       know when it is within that month/year."""
..
```

**Comment by dracos** [comment]
Thanks, this should now support Django 3, just pushing a new one to pypi now.
