### ISSUE TITLE
CommandError: Unable to serialize database: 'ApproximateDateField' object has no attribute '_get_val_from_obj'

### ISSUE THREAD

**Issue by jonancm** [dracos/django-date-extensions#26]
When I try to serialize my development database into a fixture with the command:

```console
$ python manage.py dumpdata --indent 4
```

I get the following traceback:

```
CommandError: Unable to serialize database: 'ApproximateDateField' object has no attribute '_get_val_from_obj'
Exception ignored in: <generator object cursor_iter at 0x7fd5723027b0>
Traceback (most recent call last):
  File "/home/jonancm/.cache/pypoetry/virtualenvs/gamehunter-gvZjkORE-py3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1609, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

I'm using the following software versions:

- django-date-extensions 3.1
- Django 3.1.4
- Python 3.8.5

Doing a quick research, I found a [Django ticket that deprecates this method][Django ticket #24716].

In the Django documentation on [how to write custom model fields](https://docs.djangoproject.com/en/3.1/howto/custom-model-fields/#converting-field-data-for-serialization), I found that you should use the method [value_from_object](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.Field.value_from_object) to implement the method [value_to_string](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.Field.value_to_string).

As of now, django-date-extensions implements `ApproximateDateField.value_to_string` relying on `Field._get_val_from_obj`:

https://github.com/dracos/django-date-extensions/blob/57c9673fd8f38123f348456dc9fa1f21373b3414/django_date_extensions/fields.py#L155

In the [aforementioned ticket][Django ticket #24716], you can see the `Field._get_val_from_obj` method was deprecated because it duplicates the functionality of `Field.value_from_object`.

I haven't found any other uses of `value_from_object` in the codebase, so the solution should be fairly easy: just replace `value_from_object` with `value_from_object` in line 155 of `fields.py`.

I will try this and submit a pull request if I manage to solve the issue.

[Django ticket #24716]: https://code.djangoproject.com/ticket/24716

**Comment by dracos** [comment]
Thanks also for the comprehensive and clear bug report!
